printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: consistent
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
rangeStart: 0
# rangeEnd: Infinity
# parser: html
filepath: none
requirePragma: false
insertPragma: false
proseWrap: preserve
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: false
endOfLine: auto
embeddedLanguageFormatting: auto
